nginx:
    build: lb
    links:
        - web1:web1
        - web2:web2
        - web3:web3
    ports:
        - "80:80"

web1:
  build: web
  ports:
    - "3000"
  links:
    - db
  environment:
    - PORT=3000
    - APP=bin/www

web2:
  build: web
  ports:
    - "3000"
  links:
    - db
  environment:
    - PORT=3000
    - APP=bin/www

web3:
  build: web
  ports:
    - "3000"
  links:
    - db
  environment:
    - PORT=3000
    - APP=bin/www

db:
  image: mongo
